# Generated by Django 2.2 on 2019-07-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20190716_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemphotovariant',
            name='bordered_image',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='itemphotovariant',
            name='bordered_image_region',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bordered_image_region', to='editor.WTLHA'),
        ),
    ]
