# Generated by Django 2.2 on 2019-07-17 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_auto_20190717_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemphotovariant',
            name='bordered_image_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bordered_image_region', to='editor.WTLHA'),
        ),
    ]
